### ISSUE TITLE
ov5642  parallel camera 

### ISSUE THREAD

**Issue by rohanbhargava11** [varigit/linux-2.6-imx#1]
Hi, 

I am trying to get a ov5642 parallel camera working. I have changed the imx6qdl-var-som.dtsi to include &i2c3 {
    clock-frequency = <100000>;
    pinctrl-names = "default";
    pinctrl-0 = <&pinctrl_i2c3_3>;
    status = "okay";

```
ov5642: ov5642@3c {
    compatible = "ovti,ov5642";
    reg = <0x3c>;
    clocks = <&clks 200>;
    clock-names = "csi_mclk";
```

////        DOVDD-supply = <&vgen4_reg>; /\* 1.8v _/
////        AVDD-supply = <&vgen3_reg>;  /_ 2.8v, rev C board is VGEN3 rev B board //is VGEN5 _/
////        DVDD-supply = <&vgen2_reg>;  /_ 1.5v*/
        pwn-gpios = <&gpio5 20 1>;
        rst-gpios = <&gpio5 14 0>;
        csi_id = <1>;
        mclk = <24000000>;
        mclk_source = <0>;
    };

};

When I load the driver I get an error ov5642 setup pinctrl failed!. What is the right configuration for ov5642 parallel camera. 

I build the dtsi by this command  make -j8 ARCH=arm CROSS_COMPILE=arm-fsl-linux-gnueabi- uImage LOADADDR=0x10008000 imx6q-var-som.dtb

**Comment by varigit** [comment]
Hi  Rohan
Please send support question to support@variscite.com. 
We will get back to you on this..

Ron

**Comment by rohanbhargava11** [comment]
Hi Ron,

I have already sent an email. I have been getting help from Or Sade. I just thought it would be nice to document the issue here to help other users.

**Comment by varigit** [comment]
We never used this. It create a cross channel.
I appricate if you can use the support channel.

**Comment by Radekp81** [comment]
Hi,

I am having exactly the same issue - would someone be able to share the outcome for this?

Thanks,
Radek.
