### ISSUE TITLE
MAC addresses for eth1 and eth0 are swapped

### ISSUE THREAD

**Issue by kraj** [varigit/linux-2.6-imx#5]
between imx-rel_imx_4.1.15_1.1.0_ga-var02 and imx-rel_imx_4.1.15_2.0.0_ga-var02  there is a change where MAC addresses for ethernet ports are getting swapped. This causes problem for applications which are reading the MAC addresses for the live phy and registering it in backend and suddernly they wont work with new kernel without manually chaging the new mac address in backend as well. 

I am fine if someone can point where this change happened, its ok if I have to carry a local patch

**Comment by eranmati** [comment]
Hi Khem.
If I recall correctly, the difference is in arch/arm/mach-imx/common.c, between the following two commits:
Old: cac9f1834a2e0ae0f41cf440d9ff433ae719622f
New: 00c1693bdee118a1791d6905f5d9294a177765e1

Next time, please use our customer portal for support:
http://www.variscite.com/support/variscite-customer-portal

Regards,
Eran
